[phases.setup]
nixPkgs = ["nodejs", "npm", "ffmpeg", "python3", "gcc", "gnumake", "libtool", "autoconf", "automake"]

[phases.install]
cmds = ["npm install"]

[phases.start]
cmds = ["npm run start"]
